### ISSUE TITLE
MEMORY_ONLY, MEMORY_ONLY_* storage levels

### ISSUE THREAD

**Issue by jedisct1** [dibbhatt/kafka-spark-consumer#17]
Hi,

Since the very first version of kafka-spark-consumer, the only storage level I have been able to use are the disk-based ones such as `MEMORY_AND_DISK_SER`.

Unfortunately, this requires a lot of disk operations on hosts running the Kafka receivers, and disks then become a bottleneck. Disks I/O only happen on these hosts (the ones running the receivers); I don't know if this is the expected behavior.

When using `MEMORY_ONLY` or `MEMORY_ONLY_SER`, I quickly get a slew of exceptions:

```
15/05/06 16:25:11 WARN TaskSetManager: Lost task 69.0 in stage 3.0 (TID 141, node-00263.hadoop): java.lang.Exception:
Could not compute split, block input-1-1430922252737 not found
        at org.apache.spark.rdd.BlockRDD.compute(BlockRDD.scala:51)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
        at org.apache.spark.rdd.UnionRDD.compute(UnionRDD.scala:87)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
        at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
        at org.apache.spark.rdd.FlatMappedRDD.compute(FlatMappedRDD.scala:33)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
        at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:93)
        at org.apache.spark.rdd.CoalescedRDD$$anonfun$compute$1.apply(CoalescedRDD.scala:92)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
        at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:248)
        at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:163)
        at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:70)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:228)
        at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
        at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:263)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:230)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:68)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:56)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
```

`MEMORY_ONLY_2` and `MEMORY_ONLY_SER_2` work amazingly well for a few minutes and eventually fail the same way.

Your expertise would be more than welcome.

**Comment by dibbhatt** [comment]
Hi, 

This is a very common issue in Spark Streaming . The issue here is , if you just use MEMORY_ONLY settings , it eventually get filled out ( if your job processing has some delay and not able to process blocks at same rate it arrives ) . For that Spark has some wired eviction policy where it dropped some un-processed blocks out of the memory (LRU policy I guess). But those blocks are not written to disk . So when the Job want to find a block for a given batch , which already being evicted , you see this error . 

For MEMORY_DISK case , there is another copy available in disk , so if the Job does not find the block in memory , it can find in disk. But that comes with a very high latency of disk write.

Ideally Spark need to handle this much better way. For any MEMORY based blocks when evicted , have to be persisted to disk .

recently @akhld has find a innovative solution where he modified the Spark internals to find if there is any scheduling delay , and if there are any , it will notify this Receiver ( via Zookeeper ) so that the Receiver will stop generating the block , and hence prevent any pressure on Memory. He need to discuss this further with Databricks folks before this kind of workaround can be applied . 

But yet , this is a pain in Spark Streaming .

**Comment by jedisct1** [comment]
Looking at the UI, it takes about 20 seconds to process each batch, and the batch interval is 1 minute. The number of waiting batches never exceeds 1. So doesn't that mean that the job is able to process blocks at the rate they arrive?

**Comment by akhld** [comment]
Since your batch interval is 1 minute, if you haven't changed the fillFrequency from 200ms to a higher number, then what happens is that for every batch you will be having around 300 blocks being pushed to memory. And if each block is having around 50MB of data, then you will be needing at least 15GB of memory to hold data for a batch.

Can you tell us about your configurations (cluster and receiver)?

**Comment by jedisct1** [comment]
Hi Akhil,

Do I need 15 Gb of memory per executor? Given a uniform key distribution, shouldn't it be `2x15 Gb/number of executors` for each executor?

Or do receivers actually need to keep a full batch (1 minute here, not the 200ms batch period to read from Kafka) in memory?

I need to pull 250 MB/s from Kafka. 60 Kafka partitions. 48 nodes for Spark with 64 Gb RAM, but these are also being used for HDFS and HBase.

**Comment by akhld** [comment]
15GB was just an example that i was giving. And yes what you mentioned is
correct only.

Receiver basically sends blocks meta to spark (which is by default in every
200ms) and the blocks are kept in receivers memory.

You can check this JIRA for more info on it
https://issues.apache.org/jira/browse/SPARK-7398

Here's a simple workaround that i made
http://apache-spark-developers-list.1001551.n3.nabble.com/SparkStreaming-Workaround-for-BlockNotFound-Exceptions-td12096.html

**Comment by jedisct1** [comment]
Thanks a ton for your help, @akhld !
