### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by akhld** [dibbhatt/kafka-spark-consumer#5]
I cloned the latest version and did a mvn install and it fails to build, few test cases are failing i think.
Here's the mvn stack:

	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time: 14.397s
	[INFO] Finished at: Wed Feb 11 11:39:19 UTC 2015
	[INFO] Final Memory: 27M/290M
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project kafka-spark-consumer: There are test failures.
	[ERROR] 
	[ERROR] Please refer to /root/akhld/kafka-spark-consumer/target/surefire-reports for the individual test results.
	[ERROR] -> [Help 1]
	[ERROR] 
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR] 
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

And part of these /root/akhld/kafka-spark-consumer/target/surefire-reports/TEST-consumer.kafka.KafkaServerTest.xml and /root/akhld/kafka-spark-consumer/target/surefire-reports/TEST-consumer.kafka.ZKServerTest.xml file says:

	<testcase time="1.112" classname="consumer.kafka.KafkaServerTest" name="sendMessageAndAssertValueForOffset">
	    <error message="org.apache.zookeeper.ZooKeeper.&lt;init&gt;(Ljava/lang/String;ILorg/apache/zookeeper/Watcher;Z)V" type="java.lang.NoSuchMethodError">java.lang.NoSuchMethodError: org.apache.zookeeper.ZooKeeper.&lt;init&gt;(Ljava/lang/String;ILorg/apache/zookeeper/Watcher;Z)V
		at org.apache.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29)
		at org.apache.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:169)
		at org.apache.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94)
		at org.apache.curator.HandleHolder.getZooKeeper(HandleHolder.java:55)
		at org.apache.curator.ConnectionState.reset(ConnectionState.java:219)
		at org.apache.curator.ConnectionState.start(ConnectionState.java:103)
		at org.apache.curator.CuratorZookeeperClient.start(CuratorZookeeperClient.java:188)
		at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:234)
		at consumer.kafka.ZkState.&lt;init&gt;(ZkState.java:67)
		at consumer.kafka.KafkaServerTest.setUp(KafkaServerTest.java:70)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
		at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
		at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
		at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
		at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
		at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:606)
		at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
		at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
		at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
		at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
		at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
	</error>

This is my mvn version:

	Apache Maven 3.0.4
	Maven home: /usr/share/maven
	Java version: 1.7.0_75, vendor: Oracle Corporation
	Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
	Default locale: en_US, platform encoding: UTF-8
	OS name: "linux", version: "3.16.0-0.bpo.4-amd64", arch: "amd64", family: "unix"

**Comment by dibbhatt** [comment]
Sorry my bad. I had modified the pom file and test cases to use org.apache.curator.framework.* instead earlier netflix packages, but same was not checked-in properly. This is done, do let me know if you still see test cases failing.

**Comment by akhld** [comment]
Works great! Thanks for the quick fix.

**Comment by dibbhatt** [comment]
Thanks Akhil. Closing the issue.
